server:
  servlet:
    contextPath: /api
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver
flyway:
  url: jdbc:h2:mem:db
  user: sa
  location: "file"
  password: password
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

